version: '2'
services:
    testbed-app:
        image: testbed
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testbed-mysql:3306/testbed?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=testbed-elasticsearch:9300
        ports:
            - 8080:8080
    testbed-mysql:
        extends:
            file: mysql.yml
            service: testbed-mysql
    testbed-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: testbed-elasticsearch
